language: python
python:
- 3.5
install:
- pip install -U setuptools
- pip install coveralls
script:
- coverage run --source=fizzbotz setup.py test
after_success:
- coveralls
deploy:
  provider: pypi
  user: martensm
  password:
    secure: yDoHpL8cC0RrshBib8/N1LWxs7bA6BZYREszywAHXJPYxQ3dlOArn5TBZrBTyMz57wNZdqPGwg6jAJ/fH4Uv/vwXPLblRfsfJuZNF9X93KCFIHUrHSEok/oNEaAg3RtkzGR+VFXhXMJuLRcp/snOb6Z3/FZLI5SnVONFnPqHY1dH9Py98cdvKyic2r/depw3PONEh6UifoW/7zGHmBZRE3UTXn1X70dc147YPzrciXtBdAoFypnor3aQqZEvNhGVeKiv4kMyd0lxzPOjYlRo6E7P8Zf2lP2OtkcV3MWJmu2KbbpnYlHOQ/Ga4xg+T4TJmM31ObrQJEkp4424xRti9GEQnv1NkcXSoYtBzZTwwzVYTx+CS1sHWTIfAzEHSv7j8WLU54MgZNPo61X/ZtvFddxruK0wDZ5cOnlFO1uleEgNm7rPpIFMX5hJOiTGdresAZD4eMcfCr/AIUhsmeNtxiYh5vGbtla+xHaXIHSkhodjnM7LWwlAexPczOHVjtXqZSUqXFUMZcVZR2Z7xeSvIPc8rfOSGE7KjT9Q84Sqk1woIO06C66V4iz6hH18bxxBpNwlb8kzuQi8nZQSmEla/WcFLL19IUudpQTwXevqvrX5kHvmidP1lMlBZEzFQq1E9xwXHx8AlFVXUFokXcucuxcgEmlK1M0ieOHNZc1vEHk=
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: martensm/fizzbotz
